#pragma once

enum class SystemStatus
{
    OK,

    HSM_ERROR_INIT,
    HSM_ERROR_STATUS,
    HSM_ERROR_ERASE_KEY,
    HSM_ERROR_GENERATE_KEY,
    HSM_ERROR_READ_KEY,
    HSM_ERROR_DEINIT,

    AUDIT_ERROR_DB_OPEN,
    AUDIT_ERROR_DB_READ,
    AUDIT_ERROR_DB_WRITE,

    NOK,
};