#pragma once

enum class SystemStatus
{
    OK,
    NOK,

    ERROR_FILE_NOT_FOUND,

    HSM_ERROR_INIT,
    HSM_ERROR_STATUS,
    HSM_ERROR_ERASE_KEY,
    HSM_ERROR_GENERATE_KEY_SLOT_OCCUPIED,
    HSM_ERROR_GENERATE_KEY_HW_ERROR,
    HSM_ERROR_READ_KEY_EMPTY_SLOT,
    HSM_ERROR_READ_KEY_HW_ERROR,
    HSM_ERROR_SIGN,
    HSM_ERROR_SIGN_PAYLOAD_TOO_LARGE,
    HSM_ERROR_VERIFY_INVALID_SIGNATURE,
    HSM_ERROR_VERIFY_CRYPTO_ERROR,
    HSM_ERROR_DEINIT,

    AUDIT_ERROR_DB_OPEN,
    AUDIT_ERROR_DB_READ,
    AUDIT_ERROR_DB_WRITE,
};